//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCM.Base {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDCM.Base.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ABC Browser 的本地化字符串。
        /// </summary>
        internal static string ABC_Browser {
            get {
                return ResourceManager.GetString("ABC Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About GCMLite 的本地化字符串。
        /// </summary>
        internal static string About_GCMLite {
            get {
                return ResourceManager.GetString("About GCMLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About GCMLite(Alt+A) 的本地化字符串。
        /// </summary>
        internal static string About_GCMLite_Alt_A_ {
            get {
                return ResourceManager.GetString("About GCMLite(Alt+A)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Row 的本地化字符串。
        /// </summary>
        internal static string Add_Row {
            get {
                return ResourceManager.GetString("Add Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address: NO.1 Beichen West Road, Chaoyang District, Beijing 100101 的本地化字符串。
        /// </summary>
        internal static string Address_NO_1_Beichen_West_Road__Chaoyang_District__Beijing_100101 {
            get {
                return ResourceManager.GetString("Address NO.1 Beichen West Road, Chaoyang District, Beijing 100101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application View Initialize Failed 的本地化字符串。
        /// </summary>
        internal static string Application_View_Initialize_Failed {
            get {
                return ResourceManager.GetString("Application View Initialize Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AttrMappingOptionDlg 的本地化字符串。
        /// </summary>
        internal static string AttrMappingOptionDlg {
            get {
                return ResourceManager.GetString("AttrMappingOptionDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CCInfo ID 的本地化字符串。
        /// </summary>
        internal static string CCInfo_ID {
            get {
                return ResourceManager.GetString("CCInfo ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear All(Alt+C) 的本地化字符串。
        /// </summary>
        internal static string Clear_All_Alt_C_ {
            get {
                return ResourceManager.GetString("Clear All(Alt+C)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Alias 的本地化字符串。
        /// </summary>
        internal static string Column_Alias {
            get {
                return ResourceManager.GetString("Column Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Config Dialog 的本地化字符串。
        /// </summary>
        internal static string Column_Config_Dialog {
            get {
                return ResourceManager.GetString("Column Config Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Name 的本地化字符串。
        /// </summary>
        internal static string Column_Name {
            get {
                return ResourceManager.GetString("Column Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column restrictions updated 的本地化字符串。
        /// </summary>
        internal static string Column_restrictions_updated_ {
            get {
                return ResourceManager.GetString("Column restrictions updated.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comments 的本地化字符串。
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compare with GCM 的本地化字符串。
        /// </summary>
        internal static string Compare_with_GCM {
            get {
                return ResourceManager.GetString("Compare with GCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfigColumnsDlg 的本地化字符串。
        /// </summary>
        internal static string ConfigColumnsDlg {
            get {
                return ResourceManager.GetString("ConfigColumnsDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration 的本地化字符串。
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Message 的本地化字符串。
        /// </summary>
        internal static string Confirm_Message {
            get {
                return ResourceManager.GetString("Confirm Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect GCM failed 的本地化字符串。
        /// </summary>
        internal static string Connect_GCM_failed {
            get {
                return ResourceManager.GetString("Connect GCM failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected 的本地化字符串。
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting to GCM 的本地化字符串。
        /// </summary>
        internal static string Connecting_to_GCM {
            get {
                return ResourceManager.GetString("Connecting to GCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact: (+86)010-64807462 的本地化字符串。
        /// </summary>
        internal static string Contact___86_010_64807462 {
            get {
                return ResourceManager.GetString("Contact (+86)010-64807462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © All Rights Reserved 的本地化字符串。
        /// </summary>
        internal static string Copyright_All_Rights_Reserved {
            get {
                return ResourceManager.GetString("Copyright All Rights Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Mapping 的本地化字符串。
        /// </summary>
        internal static string Custom_Mapping {
            get {
                return ResourceManager.GetString("Custom Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Check failed 的本地化字符串。
        /// </summary>
        internal static string Data_Check_failed {
            get {
                return ResourceManager.GetString("Data Check failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Check success 的本地化字符串。
        /// </summary>
        internal static string Data_Check_success {
            get {
                return ResourceManager.GetString("Data Check success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data export failed 的本地化字符串。
        /// </summary>
        internal static string Data_export_failed {
            get {
                return ResourceManager.GetString("Data export failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data export failed with error info 的本地化字符串。
        /// </summary>
        internal static string Data_export_failed_with_error_info {
            get {
                return ResourceManager.GetString("Data export failed with error info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data filter failed 的本地化字符串。
        /// </summary>
        internal static string Data_filter_failed {
            get {
                return ResourceManager.GetString("Data filter failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data filter success 的本地化字符串。
        /// </summary>
        internal static string Data_filter_success {
            get {
                return ResourceManager.GetString("Data filter success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data publish failed 的本地化字符串。
        /// </summary>
        internal static string Data_publish_failed {
            get {
                return ResourceManager.GetString("Data publish failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data publish success 的本地化字符串。
        /// </summary>
        internal static string Data_publish_success {
            get {
                return ResourceManager.GetString("Data publish success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Value 的本地化字符串。
        /// </summary>
        internal static string Default_Value {
            get {
                return ResourceManager.GetString("Default Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Designate Scope 的本地化字符串。
        /// </summary>
        internal static string Designate_Scope {
            get {
                return ResourceManager.GetString("Designate Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected 的本地化字符串。
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DownLoad from GCM 的本地化字符串。
        /// </summary>
        internal static string DownLoad_from_GCM {
            get {
                return ResourceManager.GetString("DownLoad from GCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email: office@im.ac.cn 的本地化字符串。
        /// </summary>
        internal static string Email_office_im_ac_cn {
            get {
                return ResourceManager.GetString("Email office@im.ac.cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exact Match 的本地化字符串。
        /// </summary>
        internal static string Exact_Match {
            get {
                return ResourceManager.GetString("Exact Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel file,XML document,TSV file,CSV file,JSON List file,GCMLite archive file(*.xls,*.xlsx,*.xml,*.tsv,*csv,*.jso,*.gcms)|*.xls;*.xlsx;*.xml;*.tsv;*.csv;*.jso,*.gcms 的本地化字符串。
        /// </summary>
        internal static string Excel_XML_TSV_CSV_JSON_List_mdi {
            get {
                return ResourceManager.GetString("Excel,XML,TSV,CSV,JSON List,mdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit operation execute failed 的本地化字符串。
        /// </summary>
        internal static string Exit_operation_execute_failed {
            get {
                return ResourceManager.GetString("Exit operation execute failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export(Alt+E) 的本地化字符串。
        /// </summary>
        internal static string Export_Alt_E_ {
            get {
                return ResourceManager.GetString("Export(Alt+E)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export failed 的本地化字符串。
        /// </summary>
        internal static string Export_failed {
            get {
                return ResourceManager.GetString("Export failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 export strain tree 的本地化字符串。
        /// </summary>
        internal static string export_strain_tree {
            get {
                return ResourceManager.GetString("export strain tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export success 的本地化字符串。
        /// </summary>
        internal static string Export_success {
            get {
                return ResourceManager.GetString("Export success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exported XML Validation Failed 的本地化字符串。
        /// </summary>
        internal static string Exported_XML_Validation_Failed {
            get {
                return ResourceManager.GetString("Exported XML Validation Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to check dump file 的本地化字符串。
        /// </summary>
        internal static string Failed_to_check_dump_file {
            get {
                return ResourceManager.GetString("Failed to check dump file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to check JSON list file 的本地化字符串。
        /// </summary>
        internal static string Failed_to_check_JSON_list_file {
            get {
                return ResourceManager.GetString("Failed to check JSON list file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to check text file 的本地化字符串。
        /// </summary>
        internal static string Failed_to_check_text_file {
            get {
                return ResourceManager.GetString("Failed to check text file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export and publish the XML document for GCM 的本地化字符串。
        /// </summary>
        internal static string Failed_to_export_and_publish_the_XML_document_for_GCM {
            get {
                return ResourceManager.GetString("Failed to export and publish the XML document for GCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export Excel document 的本地化字符串。
        /// </summary>
        internal static string Failed_to_export_Excel_document {
            get {
                return ResourceManager.GetString("Failed to export Excel document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to Export excel file 的本地化字符串。
        /// </summary>
        internal static string Failed_to_Export_excel_file {
            get {
                return ResourceManager.GetString("Failed to Export excel file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export JSON File 的本地化字符串。
        /// </summary>
        internal static string Failed_to_export_JSON_File {
            get {
                return ResourceManager.GetString("Failed to export JSON File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export text file 的本地化字符串。
        /// </summary>
        internal static string Failed_to_export_text_file {
            get {
                return ResourceManager.GetString("Failed to export text file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export XML document 的本地化字符串。
        /// </summary>
        internal static string Failed_to_export_XML_document {
            get {
                return ResourceManager.GetString("Failed to export XML document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import dump file 的本地化字符串。
        /// </summary>
        internal static string Failed_to_import_dump_file {
            get {
                return ResourceManager.GetString("Failed to import dump file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to Import Excel document 的本地化字符串。
        /// </summary>
        internal static string Failed_to_Import_Excel_document {
            get {
                return ResourceManager.GetString("Failed to Import Excel document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import excel file 的本地化字符串。
        /// </summary>
        internal static string Failed_to_import_excel_file {
            get {
                return ResourceManager.GetString("Failed to import excel file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import JSON list file 的本地化字符串。
        /// </summary>
        internal static string Failed_to_import_JSON_list_file {
            get {
                return ResourceManager.GetString("Failed to import JSON list file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import text file 的本地化字符串。
        /// </summary>
        internal static string Failed_to_import_text_file {
            get {
                return ResourceManager.GetString("Failed to import text file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import XML document 的本地化字符串。
        /// </summary>
        internal static string Failed_to_import_XML_document {
            get {
                return ResourceManager.GetString("Failed to import XML document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to query the detail of GCM data 的本地化字符串。
        /// </summary>
        internal static string Failed_to_query_the_detail_of_GCM_data {
            get {
                return ResourceManager.GetString("Failed to query the detail of GCM data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to query the overview of GCM data 的本地化字符串。
        /// </summary>
        internal static string Failed_to_query_the_overview_of_GCM_data {
            get {
                return ResourceManager.GetString("Failed to query the overview of GCM data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FATAL 的本地化字符串。
        /// </summary>
        internal static string FATAL {
            get {
                return ResourceManager.GetString("FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter(Alt+R) 的本地化字符串。
        /// </summary>
        internal static string Filter_Alt_R_ {
            get {
                return ResourceManager.GetString("Filter(Alt+R)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Down 的本地化字符串。
        /// </summary>
        internal static string Find_Down {
            get {
                return ResourceManager.GetString("Find Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Up 的本地化字符串。
        /// </summary>
        internal static string Find_Up {
            get {
                return ResourceManager.GetString("Find Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Front Find 的本地化字符串。
        /// </summary>
        internal static string Front_Find {
            get {
                return ResourceManager.GetString("Front Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GCM Front Find 的本地化字符串。
        /// </summary>
        internal static string GCM_Front_Find {
            get {
                return ResourceManager.GetString("GCM Front Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GCM Password 的本地化字符串。
        /// </summary>
        internal static string GCM_Password {
            get {
                return ResourceManager.GetString("GCM Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GCM Publish 的本地化字符串。
        /// </summary>
        internal static string GCM_Publish {
            get {
                return ResourceManager.GetString("GCM Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GCMLite Archive file (*.gcms)|*.gcms 的本地化字符串。
        /// </summary>
        internal static string GCMLite_Archive_file_type {
            get {
                return ResourceManager.GetString("GCMLite Archive file type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IDCM v1.0(110) 的本地化字符串。
        /// </summary>
        internal static string IDCM_v1_0_110_ {
            get {
                return ResourceManager.GetString("IDCM v1.0(110)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import failed 的本地化字符串。
        /// </summary>
        internal static string Import_failed {
            get {
                return ResourceManager.GetString("Import failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import success 的本地化字符串。
        /// </summary>
        internal static string Import_success {
            get {
                return ResourceManager.GetString("Import success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It&apos;s Crash 的本地化字符串。
        /// </summary>
        internal static string It_s_Crash {
            get {
                return ResourceManager.GetString("It\'s Crash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It&apos;s reached the end, and traverse over. 的本地化字符串。
        /// </summary>
        internal static string It_s_reached_the_end__and_traverse_over_ {
            get {
                return ResourceManager.GetString("It\'s reached the end, and traverse over.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It seems all right. 的本地化字符串。
        /// </summary>
        internal static string It_seems_all_right_ {
            get {
                return ResourceManager.GetString("It seems all right.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key Name 的本地化字符串。
        /// </summary>
        internal static string Key_Name {
            get {
                return ResourceManager.GetString("Key Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language(Alt+L) 的本地化字符串。
        /// </summary>
        internal static string Language_Alt_L_ {
            get {
                return ResourceManager.GetString("Language(Alt+L)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local data check failed. 的本地化字符串。
        /// </summary>
        internal static string Local_data_check_failed_ {
            get {
                return ResourceManager.GetString("Local data check failed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local data export to GCM XML failed. 的本地化字符串。
        /// </summary>
        internal static string Local_data_export_to_GCM_XML_failed_ {
            get {
                return ResourceManager.GetString("Local data export to GCM XML failed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local data exported success 的本地化字符串。
        /// </summary>
        internal static string Local_data_exported_success {
            get {
                return ResourceManager.GetString("Local data exported success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local data import success 的本地化字符串。
        /// </summary>
        internal static string Local_data_import_success {
            get {
                return ResourceManager.GetString("Local data import success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local data mapping to export canceled. 的本地化字符串。
        /// </summary>
        internal static string Local_data_mapping_to_export_canceled_ {
            get {
                return ResourceManager.GetString("Local data mapping to export canceled.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local data publish to GCM operation success. 的本地化字符串。
        /// </summary>
        internal static string Local_data_publish_to_GCM_operation_success_ {
            get {
                return ResourceManager.GetString("Local data publish to GCM operation success.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local data validation did not pass 的本地化字符串。
        /// </summary>
        internal static string Local_data_validation_did_not_pass {
            get {
                return ResourceManager.GetString("Local data validation did not pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local DataSet 的本地化字符串。
        /// </summary>
        internal static string Local_DataSet {
            get {
                return ResourceManager.GetString("Local DataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login GCM(Alt+G) 的本地化字符串。
        /// </summary>
        internal static string Login_GCM_Alt_G_ {
            get {
                return ResourceManager.GetString("Login GCM(Alt+G)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Case 的本地化字符串。
        /// </summary>
        internal static string Match_Case {
            get {
                return ResourceManager.GetString("Match Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Fully 的本地化字符串。
        /// </summary>
        internal static string Match_Fully {
            get {
                return ResourceManager.GetString("Match Fully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Empty 的本地化字符串。
        /// </summary>
        internal static string Not_Empty {
            get {
                return ResourceManager.GetString("Not Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice 的本地化字符串。
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline Document(Alt+D) 的本地化字符串。
        /// </summary>
        internal static string Offline_Document_Alt_D_ {
            get {
                return ResourceManager.GetString("Offline Document(Alt+D)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On GCMLite application exiting. 的本地化字符串。
        /// </summary>
        internal static string On_GCMLite_application_exiting_ {
            get {
                return ResourceManager.GetString("On GCMLite application exiting.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On Main Manager exited. 的本地化字符串。
        /// </summary>
        internal static string On_Main_Manager_exited_ {
            get {
                return ResourceManager.GetString("On Main Manager exited.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open (Alt+O) 的本地化字符串。
        /// </summary>
        internal static string Open__Alt_O_ {
            get {
                return ResourceManager.GetString("Open (Alt+O)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose a key name, it&apos;s not available. 的本地化字符串。
        /// </summary>
        internal static string Please_choose_a_key_name__it_s_not_available_ {
            get {
                return ResourceManager.GetString("Please choose a key name, it\'s not available.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Login before compare records to GCM. 的本地化字符串。
        /// </summary>
        internal static string Please_Login_before_compare_records_to_GCM_ {
            get {
                return ResourceManager.GetString("Please Login before compare records to GCM.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Login before submitting to GCM. 的本地化字符串。
        /// </summary>
        internal static string Please_Login_before_submitting_to_GCM_ {
            get {
                return ResourceManager.GetString("Please Login before submitting to GCM.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please notice the error tips shown in the data grid view, fix those errors and confirm again. 的本地化字符串。
        /// </summary>
        internal static string Please_notice_the_error_tips_shown_in_the_data_grid_view__fix_those_errors_and_confirm_again_ {
            get {
                return ResourceManager.GetString("Please notice the error tips shown in the data grid view, fix those errors and co" +
                        "nfirm again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish to GCM 的本地化字符串。
        /// </summary>
        internal static string Publish_to_GCM {
            get {
                return ResourceManager.GetString("Publish to GCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit(Alt+Q) 的本地化字符串。
        /// </summary>
        internal static string Quit_Alt_Q_ {
            get {
                return ResourceManager.GetString("Quit(Alt+Q)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 records in total. 的本地化字符串。
        /// </summary>
        internal static string records_in_total_ {
            get {
                return ResourceManager.GetString("records in total.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember 的本地化字符串。
        /// </summary>
        internal static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Local Columns 的本地化字符串。
        /// </summary>
        internal static string Reset_Local_Columns {
            get {
                return ResourceManager.GetString("Reset Local Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restrict Expression 的本地化字符串。
        /// </summary>
        internal static string Restrict_Expression {
            get {
                return ResourceManager.GetString("Restrict Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save (Alt+S) 的本地化字符串。
        /// </summary>
        internal static string Save__Alt_S_ {
            get {
                return ResourceManager.GetString("Save (Alt+S)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SavePath 的本地化字符串。
        /// </summary>
        internal static string SavePath {
            get {
                return ResourceManager.GetString("SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search(Alt+F) 的本地化字符串。
        /// </summary>
        internal static string Search_Alt_F_ {
            get {
                return ResourceManager.GetString("Search(Alt+F)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select File Type For Export 的本地化字符串。
        /// </summary>
        internal static string Select_File_Type_For_Export {
            get {
                return ResourceManager.GetString("Select File Type For Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Similarity Match 的本地化字符串。
        /// </summary>
        internal static string Similarity_Match {
            get {
                return ResourceManager.GetString("Similarity Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        internal static string Simplified_Chinese {
            get {
                return ResourceManager.GetString("Simplified Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;CCInfo Id&apos; and &apos;GCM Password&apos; should not be empty. 的本地化字符串。
        /// </summary>
        internal static string The__CCInfo_Id__and__GCM_Password__should_not_be_empty_ {
            get {
                return ResourceManager.GetString("The \'CCInfo Id\' and \'GCM Password\' should not be empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data you pasted is in the wrong format for the cell 的本地化字符串。
        /// </summary>
        internal static string The_data_you_pasted_is_in_the_wrong_format_for_the_cell {
            get {
                return ResourceManager.GetString("The data you pasted is in the wrong format for the cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The save file path should be available. 的本地化字符串。
        /// </summary>
        internal static string The_save_file_path_should_be_available_ {
            get {
                return ResourceManager.GetString("The save file path should be available.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The save file path should be available, can not be a directory. 的本地化字符串。
        /// </summary>
        internal static string The_save_file_path_should_be_available__can_not_be_a_directory_ {
            get {
                return ResourceManager.GetString("The save file path should be available, can not be a directory.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The save file path should be writeable. 的本地化字符串。
        /// </summary>
        internal static string The_save_file_path_should_be_writeable_ {
            get {
                return ResourceManager.GetString("The save file path should be writeable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The tab sheet named &apos;Core Datasets&apos; not exist, use the first tab sheet as default data scope. 的本地化字符串。
        /// </summary>
        internal static string The_tab_sheet_named__Core_Datasets__not_exist__use_the_first_tab_sheet_as_default_data_source_ {
            get {
                return ResourceManager.GetString("The tab sheet named \'Core Datasets\' not exist, use the first tab sheet as default" +
                        " data scope.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are background tasks are executing, force quit or not 的本地化字符串。
        /// </summary>
        internal static string There_are_background_tasks_are_executing__force_quit_or_not {
            get {
                return ResourceManager.GetString("There are background tasks are executing, force quit or not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are background tasks are executing, the operation in this condition is unsafe, please retry the config later. 的本地化字符串。
        /// </summary>
        internal static string There_are_background_tasks_are_executing__the_operation_in_this_condition_is_unsafe__please_retry_the_config_later_ {
            get {
                return ResourceManager.GetString("There are background tasks are executing, the operation in this condition is unsa" +
                        "fe, please retry the config later.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool 的本地化字符串。
        /// </summary>
        internal static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unique 的本地化字符串。
        /// </summary>
        internal static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unspported file type for text import. 的本地化字符串。
        /// </summary>
        internal static string Unspported_file_type_for_text_import_ {
            get {
                return ResourceManager.GetString("Unspported file type for text import.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupport export type 的本地化字符串。
        /// </summary>
        internal static string Unsupport_export_type {
            get {
                return ResourceManager.GetString("Unsupport export type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update local columns&apos; config, the application should restart, are you sure restart now? 的本地化字符串。
        /// </summary>
        internal static string Update_local_columns__config__the_application_should_restart__are_you_sure_restart_now_ {
            get {
                return ResourceManager.GetString("Update local columns\' config, the application should restart, are you sure restar" +
                        "t now?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation(Alt+V) 的本地化字符串。
        /// </summary>
        internal static string Validation_Alt_V_ {
            get {
                return ResourceManager.GetString("Validation(Alt+V)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web Support(Alt+H) 的本地化字符串。
        /// </summary>
        internal static string Web_Support_Alt_H_ {
            get {
                return ResourceManager.GetString("Web Support(Alt+H)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work process existing under this work space. Choose confirm and exit this instance. 的本地化字符串。
        /// </summary>
        internal static string Work_process_existing_under_this_work_space__Choose_confirm_and_exit_this_instance_ {
            get {
                return ResourceManager.GetString("Work process existing under this work space. Choose confirm and exit this instanc" +
                        "e.", resourceCulture);
            }
        }
    }
}
